name: GitHub Actions Demo

on:
  push:
    branches:
    - main
    paths-ignore: 
    - .github/**
  pull_request:
    branches: 
    - main
  schedule:
    - cron: "15 6 * * 0"
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true
    
jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Event: ${{ github.event_name }}"
          echo "Ref:   ${{ github.ref }}"
          
      - uses: actions/checkout@v3.3.0

      - name: List files in the repository
        run: |
          echo "Repository: ${{ github.repository }}:"
          tree    
  
  Test:
     runs-on: ubuntu-latest
     if: github.event_name == 'workflow_dispatch'
     needs: Build
     environment: Test
     steps:
       - run: echo "Testing..."
       
  Load-Test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: Build
    environment: Load-Test
    steps:
      - run: |
          echo "Testing..."
          sleep 1
          
  Production:
    runs-on: ubuntu-latest
    needs: 
      - Test
      - Load-Test
    environment:
      name: wpro
      url: https://writeabout.net
    if: github.event.inputs.environment == 'wpro'
    steps:
      - run: |
          echo "Step 1..."
          sleep 1
      - run: |
          echo "Step 2..."
          sleep 1
      - run: |
          echo "Step 3..."
          sleep 1
      - run: |
          echo "Step 4..."
          sleep 1
    
    
