name: hello-world

on:
  push:
    branches:
    - main
    paths: 
    - hello-world-docker-action/**
    - .github/workflows/hello-world-docker-ci.yml
  workflow_dispatch:
  
jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.3.0

      - name: Run container action
        id: hello-action
        uses: ./hello-world-docker-action
        with:
          who-to-greet: 'Foo'

      - name: Output time
        run: echo "The time was ${{ steps.hello-action.outputs.time }}"
        
      - run: echo "FOO ${{ steps.hello-action.inputs.who-to-greet }}" >> $GITHUB_STEP_SUMMARY
