name: Reusable workflow

on:
  workflow_call:
    inputs:
      who-to-greet:
        description: 'Who to greet'
        type: string
        required: true
        default: Nobody
    outputs:
      current-time:
        description: 'Timez for greetz:'
        value: ${{ jobs.reusable-job.outputs.current-time }}
        
jobs:
  reusable-job:
    runs-on: ubuntu-latest
    steps:
      - name: Greetz
        run: echo "Hello ${{ inputs.who-to-greet }}"
      - name: Setz
        id: time
        run: echo "time=$(date)" >> $GITHUB_OUTPUT
    outputs:
      current-time: ${{ steps.time.outputs.time }}
  
